In [4]:
import numpy as np
import pandas as pd


x = np.asmatrix([1, 3, 2, 5, 4])
x.dtype

dtype('int32')

In [2]:
# character vector as list
x = ['... Of Your Fake Dimension', 'Ephemeron', 'Dryswch', 'Isotasy', 'Memory']
x
# as np object
x = np.asarray(['... Of Your Fake Dimension', 'Ephemeron', 'Dryswch', 'Isotasy', 'Memory'])
x

array(['... Of Your Fake Dimension', 'Ephemeron', 'Dryswch', 'Isotasy',
       'Memory'],
      dtype='<U26')

In [3]:
## ----factors -----------------------------------------
x_string = np.repeat(['a', 'b', 'c'], 10)
x_factor = pd.Categorical(x_string)
x_factor
x_factor.dtype
np.sum(x_factor)             # not what you want
x_num = x_factor.codes
np.sum(x_num)                # can use as numeric 

30

In [20]:
## ----logical/boolean-------------------------------------------------------------
my_logic = np.array([True, False, True, False, True, True], dtype=bool)
type(my_logic)

array([False,  True, False,  True, False, False], dtype=bool)

In [21]:
## ----logical_demo--------------------------------------------------------
np.logical_not(my_logic)
np.mean(my_logic)

0.66666666666666663

In [28]:
## ----int_num-------------------------------------------------------------
[np.arange(3)]
# type([np.arange(3)])

np.random.randn(5)

array([-1.03415582, -0.44148099,  1.71108471, -0.05178067, -0.4060903 ])

In [4]:
## ----createMatrix--------------------------------------------------------
# vectors; note that the sequence is open on the right, i.e. will not include the stop number
x = np.arange(1,5)
y = np.arange(5,9)
z = np.arange(9,13)

np.vstack((x,y,z))   
np.hstack((x,y,z))

# or reshape to 2d matrix and use concatenate
x = np.arange(1,5).reshape(1,4)
y = np.arange(5,9).reshape(1,4)
z = np.arange(9,13).reshape(1,4)

np.concatenate((x,y,z), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
## ----list----------------------------------------------------------------
x = [1, 'apple', [3, 'cat']]
x

[1, 'apple', [3, 'cat']]

In [6]:
## ----listloop------------------------------------------------------------
for elem in x: print(type(elem))

<class 'int'>
<class 'str'>
<class 'list'>


In [7]:
## ----namedlist-----------------------------------------------------------
x = {'a':25, 'b':-1, 'c':0}
x['b']

-1

In [8]:
## ----createdf-------------------------------------------------
mydf = pd.DataFrame({'a': [1,5,2],
                     'b': [3,8,1]})

In [9]:
## ----dfrownames-----------------------------------------------
mydf.index  = {'row' + str(x) for x in np.arange(1,4)}

In [10]:
## ----dsex1, echo=F-------------------------------------------------------
mydf = pd.DataFrame({'A':[1,2,3], 'B':['a','b','c']})

In [11]:
## ----dsex2, echo=F-------------------------------------------------------
mylist = [['a','b'], [1,2,3], mydf]